[task]
deterministic = true

[requirements]
packages = ["build-essential", "libssl-dev", "john"]  

[inputs]
type = "file_single"

[inputs.file_single]
path = "rockyou_1k.txt"
index_file = "rockyou_1k.txt.idx"
index_len = 8
format = "text"
delimiter = "\n"


[runner]
command    = "python calculate.py"
arg_start  = "--start"
arg_end    = "--end"
extra_args = ""

[outputs]
dir              = "~/.john"
filename_pattern = "john.pot"
