[task]
  deterministic = true

[requirements]
  packages = ["build-essential", "libssl-dev", "john"]  

[inputs]
  type = "file_single"

[inputs.file_single]
  path = "rockyou_1k.txt"
  format = "text"
  delimiter = "\n"

[outputs]
  dir              = "~/.john"
  filename_pattern = "john.pot"
